jwt:
  secret: ${jwt.token.secret}
  validity-duration: PT3600S

external-login:
  facebook:
    graph-api-base: https://graph.facebook.com

cors:
  allowed-origins: ${allowed.origins}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}