jwt:
  secret: ${jwt.token.secret}
  validity-duration: PT72H

external-login:
  facebook:
    graph-api-base: https://graph.facebook.com

event:
  lock:
    validity-duration: PT1M
    retry-wait-millis: 500
    retry-max-attempts: 5

cors:
  allowed-origins: ${allowed.origins}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}