package com.quary.bookyourinstructor.model.event.exception;

import com.quary.bookyourinstructor.model.exception.ErrorCode;

public enum EventErrorCode implements ErrorCode {
    INVALID_CYCLIC_EVENT_BOUNDARIES,
    EVENT_BOOKING_ALREADY_LOCKED,
    EVENT_CHANGED,
    EVENT_BOOK_LOCK_EXPIRED,
    COLLIDING_CYCLIC_EVENT_REALIZATION,
    CYCLIC_EVENT_REALIZATION_BOUNDARIES_OUT_OF_EVENT_BOUNDARIES,
    CYCLIC_EVENT_FUTURE_REALIZATIONS_NOT_FOUND,
    CONCURRENT_DATA_MODIFICATION_EXCEPTION
}
