name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t quaryuj/book-your-instructor-backend:latest .

      - name: Push Docker image
        run: docker push quaryuj/book-your-instructor-backend:latest

      - name: Generate deployment ZIP package
        run: zip deploy.zip Dockerrun.aws.json

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to ElasticBenstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          application_name: book-your-instructor-backend
          environment_name: Bookyourinstructorbackend-env
          version_label: "book-your-instructor-backend-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: deploy.zip